import { findGuestByCheckinQr, parseCheckinQrPayload } from '@/lib/checkin-qr'
import { getGuestRsvpUrl } from '@/lib/public-urls'
import type { Guest } from '@/models/Guest'
import { describe, expect, it } from 'vitest'

function guest(overrides: Partial<Guest> = {}): Guest {
  return {
    id: 'guest-1',
    event_id: 'event-1',
    first_name: 'Ana',
    last_name: 'Garcia',
    pretty_token: 'ABC123',
    guests_count: 1,
    status_id: 'pending',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    ...overrides,
  } as Guest
}

describe('parseCheckinQrPayload', () => {
  it('extracts and decodes token from public RSVP URLs', () => {
    expect(parseCheckinQrPayload(' https://www.eventiapp.com.mx/rsvp/mi-evento?token=token%2F123%20%2B%23 ')).toEqual({
      raw: 'https://www.eventiapp.com.mx/rsvp/mi-evento?token=token%2F123%20%2B%23',
      token: 'token/123 +#',
      guestId: 'token/123 +#',
    })
  })

  it('keeps legacy /evento token URLs compatible', () => {
    expect(parseCheckinQrPayload('https://www.eventiapp.com.mx/evento?token=ABC123')).toMatchObject({
      token: 'ABC123',
      guestId: 'ABC123',
    })
  })

  it('accepts pretty token aliases used by RSVP integrations', () => {
    expect(parseCheckinQrPayload('https://www.eventiapp.com.mx/rsvp/mi-evento?pretty_token=ABC%2F123')).toMatchObject({
      token: 'ABC/123',
      guestId: 'ABC/123',
    })

    expect(parseCheckinQrPayload('/rsvp/mi-evento?prettyToken=PRETTY-123')).toMatchObject({
      token: 'PRETTY-123',
      guestId: 'PRETTY-123',
    })

    expect(parseCheckinQrPayload('/rsvp/mi-evento?PrettyToken=PASCAL%2F123')).toMatchObject({
      token: 'PASCAL/123',
      guestId: 'PASCAL/123',
    })
  })

  it('accepts invitation token aliases and backend ByToken path URLs', () => {
    expect(parseCheckinQrPayload('/rsvp/mi-evento?invitation_token=INV%2F123')).toMatchObject({
      token: 'INV/123',
      guestId: 'INV/123',
    })

    expect(parseCheckinQrPayload('/rsvp/mi-evento?InvitationToken=INV-PASCAL')).toMatchObject({
      token: 'INV-PASCAL',
      guestId: 'INV-PASCAL',
    })

    expect(parseCheckinQrPayload('/rsvp/mi-evento?Token=RAW-PASCAL')).toMatchObject({
      token: 'RAW-PASCAL',
      guestId: 'RAW-PASCAL',
    })

    expect(parseCheckinQrPayload('/api/invitations/ByToken/PATH%2F123%20%2B%23')).toMatchObject({
      token: 'PATH/123 +#',
      guestId: 'PATH/123 +#',
    })
  })

  it('keeps legacy invitation payloads compatible', () => {
    expect(parseCheckinQrPayload(' invitation_guest-99 ')).toEqual({
      raw: 'invitation_guest-99',
      token: 'invitation_guest-99',
      guestId: 'guest-99',
    })
  })

  it('extracts token and guest id from JSON scanner payloads', () => {
    expect(parseCheckinQrPayload('{"pretty_token":"ABC/123","guest_id":"guest-json"}')).toEqual({
      raw: '{"pretty_token":"ABC/123","guest_id":"guest-json"}',
      token: 'ABC/123',
      guestId: 'guest-json',
    })

    expect(parseCheckinQrPayload('{"invitation_token":"INV/123","guest_id":"guest-invite"}')).toEqual({
      raw: '{"invitation_token":"INV/123","guest_id":"guest-invite"}',
      token: 'INV/123',
      guestId: 'guest-invite',
    })

    expect(parseCheckinQrPayload('{"token":"RAW/123"}')).toMatchObject({
      token: 'RAW/123',
      guestId: 'RAW/123',
    })

    expect(
      parseCheckinQrPayload('{"data":{"invitation":{"prettyToken":"NESTED/123"},"guest":{"ID":"guest-nested"}}}')
    ).toMatchObject({
      token: 'NESTED/123',
      guestId: 'guest-nested',
    })
  })

  it('keeps malformed JSON payloads as raw token fallbacks', () => {
    expect(parseCheckinQrPayload('{"pretty_token":')).toEqual({
      raw: '{"pretty_token":',
      token: '{"pretty_token":',
      guestId: '{"pretty_token":',
    })
  })
})

describe('findGuestByCheckinQr', () => {
  it('matches a guest from the same RSVP URL generated by dashboard sharing', () => {
    const target = guest({ id: 'guest-token', pretty_token: 'token/123 +#' })
    const url = getGuestRsvpUrl({ pretty_token: ' token/123 +# ' } as Guest, 'evento')

    expect(findGuestByCheckinQr([target], ` ${url} `).guest?.id).toBe('guest-token')
  })

  it('matches pretty_token RSVP URLs generated outside dashboard sharing', () => {
    const target = guest({ id: 'guest-pretty-token', pretty_token: 'ABC/123' })

    expect(
      findGuestByCheckinQr([target], 'https://www.eventiapp.com.mx/rsvp/mi-evento?pretty_token=ABC%2F123').guest?.id
    ).toBe('guest-pretty-token')
  })

  it('matches guests that still carry backend token casing aliases', () => {
    const target = guest({
      id: 'fallback',
      PrettyToken: 'PASCAL/123',
      invitation_token: 'INV/123',
      invitationToken: 'INV-CAMEL',
      Token: 'RAW-PASCAL',
      RSVPTokenID: 'raw-token-id',
    } as unknown as Partial<Guest>)

    expect(findGuestByCheckinQr([target], '/rsvp/mi-evento?prettyToken=PASCAL%2F123').guest?.id).toBe('fallback')
    expect(findGuestByCheckinQr([target], '/rsvp/mi-evento?invitation_token=INV%2F123').guest?.id).toBe('fallback')
    expect(findGuestByCheckinQr([target], '/rsvp/mi-evento?invitationToken=INV-CAMEL').guest?.id).toBe('fallback')
    expect(findGuestByCheckinQr([target], '/rsvp/mi-evento?Token=RAW-PASCAL').guest?.id).toBe('fallback')
    expect(findGuestByCheckinQr([target], '/rsvp/mi-evento?token=raw-token-id').guest?.id).toBe('fallback')
  })

  it('matches raw email and normalized name fallbacks', () => {
    const target = guest({ id: 'guest-email', email: 'ana@example.com' })

    expect(findGuestByCheckinQr([target], ' ana@example.com ').guest?.id).toBe('guest-email')
    expect(findGuestByCheckinQr([target], 'ana-garcia').guest?.id).toBe('guest-email')
  })

  it('matches adapter-cased guest ids and names', () => {
    const target = {
      ID: 'guest-pascal',
      FirstName: 'Luis',
      LastName: 'Perez',
    } as unknown as Guest

    expect(findGuestByCheckinQr([target], 'guest-pascal').guest).toBe(target)
    expect(findGuestByCheckinQr([target], 'luis-perez').guest).toBe(target)
  })

  it('matches guests from JSON scanner payloads by token or guest id', () => {
    const tokenTarget = guest({ id: 'guest-token-json', pretty_token: 'ABC/123' })
    const idTarget = guest({ id: 'guest-id-json', pretty_token: 'OTHER' })

    expect(findGuestByCheckinQr([tokenTarget], '{"pretty_token":"ABC/123","guest_id":"missing"}').guest?.id).toBe(
      'guest-token-json'
    )
    expect(findGuestByCheckinQr([idTarget], '{"guest_id":"guest-id-json"}').guest?.id).toBe('guest-id-json')
  })
})
